# Generated by Django 5.0.4 on 2024-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
